### ISSUE TITLE
support JSON Schema 2019-09 (formerly draft-08)

### ISSUE THREAD

**Issue by emiltin** [davishmcclurg/json_schemer#44] opened 2019-09-23 09:33 UTC

**Comment by emiltin** [comment] 2019-12-02 09:31
https://json-schema.org/draft/2019-09/release-notes.html

**Comment by leh** [comment] 2021-03-07 09:56
Hey, are there any plans to support 2019-09-validation as well?

**Comment by davishmcclurg** [comment] 2021-04-03 18:45
> Hey, are there any plans to support 2019-09-validation as well?

Supporting 2019-09 would include validation.

---

Looks like there's a new 2020-12 version as well.

**Comment by dbourguignon** [comment] 2021-12-23 09:31
👋 Any news on that?
It seems that the 2020-12 version is the one targeted by OpenAPI 3.1, it would interesting to make it supported there

**Comment by davishmcclurg** [comment] 2021-12-26 21:02
> 👋 Any news on that?
> It seems that the 2020-12 version is the one targeted by OpenAPI 3.1, it would interesting to make it supported there

No news at the moment. I recently quit my job though so I may have more time to look into the changes.

**Comment by emiltin** [comment] 2022-04-05 07:37
hi @davishmcclurg, thank you for a great gem! any news on supporting 2019-09 or 2020-12?

**Comment by kyrofa** [comment] 2022-11-22 18:55
I'd love to see this as well.

**Comment by ekzobrain** [comment] 2023-06-22 09:35
@davishmcclurg I started working on this here: https://github.com/ekzo-dev/json_schemer/tree/feature/draft2019-09
I currently implemented only this core change https://json-schema.org/draft/2019-09/release-notes.html#keyword-changes:
$ref | changed | Other keywords are now allowed alongside of it

I also adjusted test suite to run draft2019-09 ref tests, but some of them still fail because some other core changes need to be implemented as well.
I will continue this work step by step, and it would be great if you patricipate as well.

**Comment by davishmcclurg** [comment] 2023-07-09 20:50
Hi @ekzobrain—I appreciate the contribution! I've actually been working for the last couple months on a rewrite to support the latest drafts: https://github.com/davishmcclurg/json_schemer/compare/next

There are a lot of changes there so I probably won't be able to include yours, but let me know if you want to help out elsewhere because there are still some things to finish up.

**Comment by ekzobrain** [comment] 2023-07-10 10:02
@davishmcclurg Hi. You've done a great work! I may help with testing - we have tens of thousands compex schemas (some of them are up to 8000 rows in source), which are now build on Draft 7, bu we need to migrate them to at least Draft 2019-09, or may be even 2020-12 as you already support it. What is the currect state of your work, what's remaining undone?
While working with your current (Draft 7) implementation we also faced issues with ambiguous error output. Some times it is very hard to understand what is the source of the error when validating complex structured schemas with allOf/oneOf keywords. This validator https://www.jsonschemavalidator.net/ (supports only up to Draft 2019-09) gives very good error descriptions, it would be great to implement identically. If you wish I may provide examples.

**Comment by ekzobrain** [comment] 2023-07-19 09:37
Ok, I'll give you feedback about my tests and error output in about a week

**Comment by davishmcclurg** [comment] 2023-07-25 20:30
@ekzobrain I just added a commit to that branch that adds more descriptive error messages. I don't think it addresses your concerns (eg, `additionaProperties`) but it should cover what people are using `JSONSchemer::Errors.pretty` for.

**Comment by davishmcclurg** [comment] 2023-08-03 22:13
> Ok, I'll give you feedback about my tests and error output in about a week

@ekzobrain have you had a chance to test things out? I've got a [PR](https://github.com/davishmcclurg/json_schemer/pull/135) open now that I'm planning to merge in a couple weeks. It would be helpful if you could test it out before I merge. Let me know!

**Comment by davishmcclurg** [comment] 2023-08-07 02:10
Thanks @neilpa-inv! I appreciate the feedback

**Comment by ekzobrain** [comment] 2023-08-18 19:32
@davishmcclurg I've started testing against my files and faced an issue with Draft 7 schema. I've attached an example schema and data files.

This code throws an exception:
```ruby
schemer = JSONSchemer.schema(Pathname.new('schema.json'))
schemer.validate(Pathname.new('data.json'))
```

While this code returns `true`:
```ruby
JSONSchemer.valid_schema?(Pathname.new('schema.json'))
```
[example.zip](https://github.com/davishmcclurg/json_schemer/files/12383502/example.zip)

**Comment by davishmcclurg** [comment] 2023-08-18 20:56
> This code throws an exception "JSONSchemer::InvalidRefPointer: /definitions/n1:TStatementForm1":

Looks like the issue is you're using other keywords (ie, `definitions`) at the same level as `$ref`. That's not allowed in [Draft 7](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-01#section-8.3):

> All other properties in a "$ref" object MUST be ignored.

To get around it, you can wrap the `$ref` in `allOf`:

```json
"allOf": [{ "$ref": "#/definitions/n1:TStatementForm1" }],
```

**Comment by neilpa-inv** [comment] 2023-08-18 21:02
> > This code throws an exception "JSONSchemer::InvalidRefPointer: /definitions/n1:TStatementForm1":
> 
> Looks like the issue is you're using other keywords (ie, `definitions`) at the same level as `$ref`. That's not allowed in [Draft 7](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-01#section-8.3):
> 
> > All other properties in a "$ref" object MUST be ignored.
> 
> To get around it, you can wrap the `$ref` in `allOf`:
> 
> ```json
> "allOf": [{ "$ref": "#/definitions/n1:TStatementForm1" }],
> ```

But shouldn't the `JSONSchemer.valid_schema?` call also fail for the same invalid ref?

**Comment by davishmcclurg** [comment] 2023-08-18 21:21
> But shouldn't the `JSONSchemer.valid_schema?` call also fail for the same invalid ref?

`valid_schema?` only validates the provided schema against the [published meta schema](http://json-schema.org/draft-07/schema#), which doesn't cover this case. If you look at the published schema, it's fairly simple and won't guarantee that a schema is correct. `valid_schema?` also does not resolve any refs because it treats the provided schema as any other JSON data.

**Comment by ekzobrain** [comment] 2023-08-19 01:24
> > This code throws an exception "JSONSchemer::InvalidRefPointer: /definitions/n1:TStatementForm1":
> 
> Looks like the issue is you're using other keywords (ie, `definitions`) at the same level as `$ref`. That's not allowed in [Draft 7](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-01#section-8.3):
> 
> > All other properties in a "$ref" object MUST be ignored.
> 
> To get around it, you can wrap the `$ref` in `allOf`:
> 
> ```json
> "allOf": [{ "$ref": "#/definitions/n1:TStatementForm1" }],
> ```

I know about this rule, but always thought, that it is relative only for validation vocabulary keywords. Your 1.0 version worked correct with this schema and other validators that I know adn use also handle it correctly, for example: https://www.jsonschemavalidator.net/

**Comment by davishmcclurg** [comment] 2023-08-19 02:00
> I know about this rule, but always thought, that it is relative only for validation vocabulary keywords.

I don't think that's the case since there's a json-schema-test-suite test for ignoring `$id` when it's next to `$ref`: https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/5cc9214e82f1e0a5e9644960b6fe0166afb7b283/tests/draft7/ref.json#L178-L213

Looks like the `definitions` case is controversial though: https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/458

I'll look into supporting `definitions` since that's the previous behavior.

**Comment by davishmcclurg** [comment] 2023-08-19 02:39
@ekzobrain I updated that branch to make `definitions` work as you described. Let me know if you have any trouble.

**Comment by ekzobrain** [comment] 2023-08-19 11:28
@davishmcclurg It now works as expected.
Now about error messages. I've updated my example files to fail with additionalProperties error. The schema is complex enough, it contains oneOf/allOf branches and when an error occures in some branch - it is very hard to find out and locate an actual problem. One of the major problems is that oneOf has no separate error message when it does not pass validation, but it should.
Run this code:
```ruby
schemer = JSONSchemer.schema(Pathname.new('schema.json'))
e = schemer.validate(JSON.parse(File.read('data.json')))
e.each { |e| puts e['error'] } # or JSONSchemer::Errors.pretty(e)
``` 
And compare output with this validator: https://www.jsonschemavalidator.net/ , it gives a correct error tree for all nested schemas and it is easy to find an actual source of the problem.
Also text for additionalProperties error is much cleaner there.

It would be great to try to mimic their output messages as close as possible.

 
[example2.zip](https://github.com/davishmcclurg/json_schemer/files/12385737/example2.zip)

**Comment by ekzobrain** [comment] 2023-08-19 11:33
And another notice is about public API. JSONSchemer.validate() method supports passing a Pathname, but resolved file contents is processed as string and not JSON.parse()'d as JSONSchemer.schema() does.
I think it would be better to align this behavior and parse data file contents as JSON if it is given as a Pathname.
Currenly this won't work:
```ruby
schemer = JSONSchemer.schema(Pathname.new('schema.json'))
schemer.valid?(Pathname.new('data.json'))
```

**Comment by davishmcclurg** [comment] 2023-08-19 17:48
> And compare output with this validator: https://www.jsonschemavalidator.net/ , it gives a correct error tree for all nested schemas (especially for oneOf) and it is easy to find an actual source of the problem.

If you want a tree of errors, try `output_format: 'detailed'`. The output is more verbose than jsonschemavalidator.net, but it's similar:

<details>
<summary>"detailed" output</summary>

```json
{
  "valid": false,
  "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf",
  "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf",
  "instanceLocation": "/header/appliedDocument/0",
  "error": "instance at `/header/appliedDocument/0` does not match exactly one `oneOf` schema",
  "errors": [
    {
      "valid": false,
      "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/0/properties/otherDocument/$ref/properties/documentTypes/items/$ref/oneOf",
      "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:DocumentTypes/oneOf",
      "instanceLocation": "/header/appliedDocument/0/otherDocument/documentTypes/0",
      "error": "instance at `/header/appliedDocument/0/otherDocument/documentTypes/0` does not match exactly one `oneOf` schema",
      "errors": [
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/0/properties/otherDocument/$ref/properties/documentTypes/items/$ref/oneOf/0/additionalProperties",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:DocumentTypes/oneOf/0/additionalProperties",
          "instanceLocation": "/header/appliedDocument/0/otherDocument/documentTypes/0/testAddProp",
          "error": "instance at `/header/appliedDocument/0/otherDocument/documentTypes/0/testAddProp` does not match schema"
        },
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/0/properties/otherDocument/$ref/properties/documentTypes/items/$ref/oneOf/1",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:DocumentTypes/oneOf/1",
          "instanceLocation": "/header/appliedDocument/0/otherDocument/documentTypes/0",
          "error": "instance at `/header/appliedDocument/0/otherDocument/documentTypes/0` does not match schema",
          "errors": [
            {
              "valid": false,
              "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/0/properties/otherDocument/$ref/properties/documentTypes/items/$ref/oneOf/1/propertyNames/pattern",
              "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:DocumentTypes/oneOf/1/propertyNames/pattern",
              "instanceLocation": "/header/appliedDocument/0/otherDocument/documentTypes/0",
              "error": "string at `/header/appliedDocument/0/otherDocument/documentTypes/0` does not match pattern: ^(?!documentTypeCode$).*"
            },
            {
              "valid": false,
              "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/0/properties/otherDocument/$ref/properties/documentTypes/items/$ref/oneOf/1/required",
              "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:DocumentTypes/oneOf/1/required",
              "instanceLocation": "/header/appliedDocument/0/otherDocument/documentTypes/0",
              "error": "hash at `/header/appliedDocument/0/otherDocument/documentTypes/0` is missing required keys: [\"representativeDocTypeCode\"]"
            }
          ]
        }
      ]
    },
    {
      "valid": false,
      "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/1",
      "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/1",
      "instanceLocation": "/header/appliedDocument/0",
      "error": "instance at `/header/appliedDocument/0` does not match schema",
      "errors": [
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/1/propertyNames/pattern",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/1/propertyNames/pattern",
          "instanceLocation": "/header/appliedDocument/0",
          "error": "string at `/header/appliedDocument/0` does not match pattern: ^(?!otherDocument$|idDocument$|powerOfAttorney$|mapPlanDocument$|legalAct$|confirmPrivilege$).*"
        },
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/1/required",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/1/required",
          "instanceLocation": "/header/appliedDocument/0",
          "error": "hash at `/header/appliedDocument/0` is missing required keys: [\"paymentDocument\"]"
        }
      ]
    },
    {
      "valid": false,
      "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/2",
      "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/2",
      "instanceLocation": "/header/appliedDocument/0",
      "error": "instance at `/header/appliedDocument/0` does not match schema",
      "errors": [
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/2/propertyNames/pattern",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/2/propertyNames/pattern",
          "instanceLocation": "/header/appliedDocument/0",
          "error": "string at `/header/appliedDocument/0` does not match pattern: ^(?!otherDocument$|paymentDocument$|powerOfAttorney$|mapPlanDocument$|legalAct$|confirmPrivilege$).*"
        },
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/2/required",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/2/required",
          "instanceLocation": "/header/appliedDocument/0",
          "error": "hash at `/header/appliedDocument/0` is missing required keys: [\"idDocument\"]"
        }
      ]
    },
    {
      "valid": false,
      "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/3",
      "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/3",
      "instanceLocation": "/header/appliedDocument/0",
      "error": "instance at `/header/appliedDocument/0` does not match schema",
      "errors": [
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/3/propertyNames/pattern",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/3/propertyNames/pattern",
          "instanceLocation": "/header/appliedDocument/0",
          "error": "string at `/header/appliedDocument/0` does not match pattern: ^(?!otherDocument$|paymentDocument$|idDocument$|mapPlanDocument$|legalAct$|confirmPrivilege$).*"
        },
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/3/required",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/3/required",
          "instanceLocation": "/header/appliedDocument/0",
          "error": "hash at `/header/appliedDocument/0` is missing required keys: [\"powerOfAttorney\"]"
        }
      ]
    },
    {
      "valid": false,
      "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/4",
      "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/4",
      "instanceLocation": "/header/appliedDocument/0",
      "error": "instance at `/header/appliedDocument/0` does not match schema",
      "errors": [
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/4/propertyNames/pattern",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/4/propertyNames/pattern",
          "instanceLocation": "/header/appliedDocument/0",
          "error": "string at `/header/appliedDocument/0` does not match pattern: ^(?!otherDocument$|paymentDocument$|idDocument$|powerOfAttorney$|legalAct$|confirmPrivilege$).*"
        },
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/4/required",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/4/required",
          "instanceLocation": "/header/appliedDocument/0",
          "error": "hash at `/header/appliedDocument/0` is missing required keys: [\"mapPlanDocument\"]"
        }
      ]
    },
    {
      "valid": false,
      "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/5",
      "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/5",
      "instanceLocation": "/header/appliedDocument/0",
      "error": "instance at `/header/appliedDocument/0` does not match schema",
      "errors": [
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/5/propertyNames/pattern",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/5/propertyNames/pattern",
          "instanceLocation": "/header/appliedDocument/0",
          "error": "string at `/header/appliedDocument/0` does not match pattern: ^(?!otherDocument$|paymentDocument$|idDocument$|powerOfAttorney$|mapPlanDocument$|confirmPrivilege$).*"
        },
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/5/required",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/5/required",
          "instanceLocation": "/header/appliedDocument/0",
          "error": "hash at `/header/appliedDocument/0` is missing required keys: [\"legalAct\"]"
        }
      ]
    },
    {
      "valid": false,
      "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/6",
      "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/6",
      "instanceLocation": "/header/appliedDocument/0",
      "error": "instance at `/header/appliedDocument/0` does not match schema",
      "errors": [
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/6/propertyNames/pattern",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/6/propertyNames/pattern",
          "instanceLocation": "/header/appliedDocument/0",
          "error": "string at `/header/appliedDocument/0` does not match pattern: ^(?!otherDocument$|paymentDocument$|idDocument$|powerOfAttorney$|mapPlanDocument$|legalAct$).*"
        },
        {
          "valid": false,
          "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/6/required",
          "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:TSomeDocument/oneOf/6/required",
          "instanceLocation": "/header/appliedDocument/0",
          "error": "hash at `/header/appliedDocument/0` is missing required keys: [\"confirmPrivilege\"]"
        }
      ]
    }
  ]
}
```

</details>

Is that close to what you're hoping for?

> And another notice is about public API. JSONSchemer.validate() method supports passing a Pathname, but resolved file contents is processed as string and not JSON.parse()'d as JSONSchemer.schema() does.
> I think it would be better to align this behavior and parse data file contents as JSON if it is given as a Pathname.

That's an interesting idea. I'm hesitant because `JSONSchemer.schema` also automatically parses strings as json, which I don't think we'd want to do for `JSONSchemer::Schema#validate` (because bare strings can be validated by a schema). I'm going to hold off on `Pathname` support for now, but please open a separate issue to discuss it further.

**Comment by ekzobrain** [comment] 2023-08-19 18:27
Ok, that's what I was looking for! But some notice about error messages:
<img width="1391" alt="Снимок экрана 2023-08-19 в 22 19 00" src="https://github.com/davishmcclurg/json_schemer/assets/2089893/220db5ea-ad3d-493e-b628-8cab8669c6d2">

1. error says: "instance at `/header/appliedDocument/0/otherDocument/documentTypes/0/testAddProp` does not match schema", but that is misleading. "Property 'testAddProp' has not been defined and the schema does not allow additional properties." is much clearer, do you agree? May it be fixed someway?
2. this is an agregate message for oneOf/1 , that it doesn't match schema. But why there was no such grouping message for oneOf/0 ? Isn't it redundant? jsonschemavalidator does not have it
3. "string at `/header/appliedDocument/0/otherDocument/documentTypes/0` does not match pattern: ^(?!documentTypeCode$).*" but there's not string at that path, there's an object... message (or instance path) should be fixed someway to express correctly
4. "hash at `/header/appliedDocument/0/otherDocument/documentTypes/0` is missing required keys: [\"representativeDocTypeCode\"]" may it be "hash at `/header/appliedDocument/0/otherDocument/documentTypes/0` is missing required keys: representativeDocTypeCode, xxx, yyy" for cleanless?

**Comment by ekzobrain** [comment] 2023-08-19 19:37
I also faced an issue with contentMediaType. A have shemas with contentMediaType: "text/xml".
Validation against such shemas throw an exception 
<img width="621" alt="Снимок экрана 2023-08-19 в 23 30 31" src="https://github.com/davishmcclurg/json_schemer/assets/2089893/d94f4e5a-5352-4a1b-a7ba-468520877c5a">

Maybe you could add a configuration callback for validating unknown contentMediaType/format ?

**Comment by davishmcclurg** [comment] 2023-08-19 20:29
> 1. error says: "instance at `/header/appliedDocument/0/otherDocument/documentTypes/0/testAddProp` does not match schema", but that is misleading. "Property 'testAddProp' has not been defined and the schema does not allow additional properties." is much clearer, do you agree? May it be fixed someway?

I updated the branch to show a more useful error message:

```json
{
  "valid": false,
  "keywordLocation": "/$ref/properties/header/$ref/properties/appliedDocument/items/$ref/oneOf/0/properties/otherDocument/$ref/properties/documentTypes/items/$ref/oneOf/0/additionalProperties",
  "absoluteKeywordLocation": "file:///Users/dharsha/Downloads/example2/schema.json#/definitions/n1:DocumentTypes/oneOf/0/additionalProperties",
  "instanceLocation": "/header/appliedDocument/0/otherDocument/documentTypes/0/testAddProp",
  "error": "property at `/header/appliedDocument/0/otherDocument/documentTypes/0/testAddProp` is not defined and schema does not allow additional properties"
}
```

> 2\. this is an agregate message for oneOf/1 , that it doesn't match schema. But why there was no such grouping message for oneOf/0 ? Isn't it redundant? jsonschemavalidator does not have it. Also it's intance path is the same as in the next two errors, that's also misleading, because one error says "instance", second "string", third "hash" pointing at the same instance path :) That's also a pros for removing it

I believe the behavior currently matches what's in the spec for the [detailed output format](https://json-schema.org/draft/2020-12/json-schema-core.html#section-12.4.3), specifically:

> The following rules govern the construction of the results object:
> - All applicator keywords ("*Of", "$ref", "if"/"then"/"else", etc.) require a node.
> - Nodes that have no children are removed.
> - Nodes that have a single child are replaced by the child.

That's likely why `oneOf/0` doesn't have the grouping message (single child replaced by child).

> 3\. "string at `/header/appliedDocument/0/otherDocument/documentTypes/0` does not match pattern: ^(?!documentTypeCode$).*" but there's not string at that path, there's an object... message (or instance path) should be fixed someway to express correctly

This one's tricky because it's a `propertyNames` error and there's not a good way to provide a json pointer path to a key (only a value).

> 4\. "hash at `/header/appliedDocument/0/otherDocument/documentTypes/0` is missing required keys: ["representativeDocTypeCode"]" may it be "hash at `/header/appliedDocument/0/otherDocument/documentTypes/0` is missing required keys: representativeDocTypeCode, xxx, yyy" for cleanless?

Yes, I updated this as well.

> I also faced an issue with contentMediaType. A have shemas with contentMediaType: "text/xml".

Did this work in previous versions? I believe `application/json` is the only media type that ever worked: https://github.com/davishmcclurg/json_schemer/blob/be345af4b3eb1f4d4feefefc170be7536b2afeeb/lib/json_schemer/schema/base.rb#L441-L448

**Comment by ekzobrain** [comment] 2023-08-19 20:35
> Did this work in previous versions? I believe application/json is the only media type that ever worked: 
seems like this is a new schema and I did not try it with previous versions... But that doesn't change my suggestion to add callback options for those :)

**Comment by ekzobrain** [comment] 2023-08-19 20:46
Also I think it is better to rename "hash" to "object" in error messages, to stick closer to JSON type names.

**Comment by davishmcclurg** [comment] 2023-08-20 17:10
> Seems like this is a new schema and I did not try it with previous versions... But that doesn't change my suggestion to add callback options for those :)

👍 please open a separate issue to keep track of the suggestion.

> Also I think it is better to rename `hash` to `object` in error messages, to stick closer to JSON type names. As you renamed `keys` to `properties`.

Good call.

---

@ekzobrain I appreciate the testing and suggestions. Did you run into any other issues testing things out with your schemas?

**Comment by ekzobrain** [comment] 2023-08-20 20:21
> @ekzobrain I appreciate the testing and suggestions. Did you run into any other issues testing things out with your schemas?

Currently not. I think it's time to make a release, if you are ready, and then move forward.

**Closed** 2023-08-20 20:59 UTC
