### ISSUE TITLE
Resolving nested $refs

### ISSUE THREAD

**Issue by ahx** [davishmcclurg/json_schemer#202] opened 2024-12-19 09:06 UTC
Hi!

UPDATE: This more a feature idea than a problem with the current  behavior.

Given I have an OpenAPI document that uses components/pathItems like this:

```yaml
# [...]
paths:
  /stations:
    $ref: '#/components/pathItems/stations'
components:
  pathItems:
    stations:
      get:
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: object
```

My assumption was that using a pointer to reference the response content schema like this should work, but it does not:

```ruby
document.ref('#/paths/~1stations/get/responses/200/content/application~1json/schema')
# =>  JSONSchemer::InvalidRefPointer: /paths/~1stations/get/responses/200/content/application~1json/schema
```

I think I misunderstood what json_schemer does here. It can handle $refs inside the target schema during validation, but it does not resolve "through" refs while looking for that target. Is that a about right?

When I change the OAD to not use $refs the pointer works.
I have added a failing test [in this PR](https://github.com/davishmcclurg/json_schemer/pull/201/files).

**Comment by ahx** [comment] 2024-12-19 13:01
I think I misunderstood what json_schemer does here. It can handle $refs inside the target schema during validation, but it does not resolve "through" refs while looking for that target. Is that a about right?

**Comment by davishmcclurg** [comment] 2024-12-22 02:42
Hey @ahx. I think this is expected behavior—`Schema#ref` acts just like `$ref` under the hood:

```
?> schema = {
?>   "$defs": {
?>     "example1": {
?>       "$ref": "#/$defs/example2"
?>     },
?>     "example2": {
?>       "allOf": [
?>         { "type": "string" }
?>       ]
?>     }
?>   },
?>   "$ref": "#/$defs/example1/allOf/0"
>> }
=> {:$defs=>{:example1=>{:$ref=>"#/$defs/example2"}, :example2=>{:allOf=>[{:type=>"string"}]}}, :$ref=>"#/$defs/example1/allOf/0"}
>> JSONSchemer.schema(schema).valid?('x')
/Users/dharsha/repos/json_schemer/lib/json_schemer/schema.rb:205:in `rescue in block in resolve_ref': /$defs/example1/allOf/0 (JSONSchemer::InvalidRefPointer)
```

Meaning it doesn't resolve "through" refs, because `$ref` uses lexical scope (I think that's the right terminology?). I believe this is correct, but let me know if you think otherwise.

Here's an example where you'd run into an issue resolving through refs (which `allOf` to follow):

```json
 {
  "$defs": {
    "example1": {
      "$ref": "#/$defs/example2",
      "allOf": [
        { "type": "integer" }
      ] 
    },
    "example2": {
      "allOf": [
        { "type": "string" }
      ]
    }
  },
  "$ref": "#/$defs/example1/allOf/0"
}
```

**Comment by ahx** [comment] 2024-12-22 20:12
Yes. I agree that the current behavior is correct.
For openapi_first I would like to dig through an OpenAPI document to get a Schema out of it with the current context. But Schema#ref is not the place to have that. 

Let me think for a while how to get there outside of json_schemer. Thanks for looking into this.

**Comment by davishmcclurg** [comment] 2024-12-23 08:10
> Let me think for a while how to get there outside of json_schemer. Thanks for looking into this.

No problem—let me know what you come up with.

**Closed by davishmcclurg** 2024-12-23 08:10 UTC
