### ISSUE TITLE
support for local ref schemas

### ISSUE THREAD

**Issue by rhuang** [davishmcclurg/json_schemer#73] opened 2020-08-20 03:09 UTC
My schema is complex with lots of reusable components, and they are split into multiple schema files. I took a quick look at the source, but it looks like this doesn't support loading multiple schemas? For example, [AJV](https://ajv.js.org/) is a popular JSON schema validator in JavaScript and it supports loading multiple schema files.

I'm trying to get the below code to work:

```
# json_schema_validator.rb
schemer = JSONSchemer.schema(Pathname.new(Rails.root.join(..., 'config', 'config_mapper.json')))
raw = YAML.load_file(..., 'input', 'input.yaml'))
schemer.validate(raw).to_a
```

```
validator/json_schema_validator.rb
validator/config/config_mapper.json
validator/config/mappers.json
validator/input/input.yaml
```
JSON schema files at: https://gist.github.com/rhuang/2e4b21bb1fb7b52a14a4a18b02a1dd7c

Running into: `JSONSchemer::InvalidFileURI (must use `file` scheme)`, can someone please advise?

It also looks like this library doesn't support:

`$ref: mappers.json/Mapper`
```
# mappers.json
SomeMapper:
  type: object
OtherMapper:
  type: object
Mapper:
  oneOf: [SomeMapper, OtherMapper]
```

Is there a way to get this format to work?

**Comment by davishmcclurg** [comment] 2020-09-28 17:12
It looks like the issue is that `$id` is set in config_mapper.json: https://gist.github.com/rhuang/2e4b21bb1fb7b52a14a4a18b02a1dd7c#file-config_mapper-json-L2

JSONSchemer uses `$id` as the URI when resolving refs: https://github.com/davishmcclurg/json_schemer/blob/74134ef2ab674f2e5a572738ffb0e44b9dee1fc1/lib/json_schemer/schema/base.rb#L86-L88

And sets `$id` (if it's not already set) when a `Pathname` is passed in: https://github.com/davishmcclurg/json_schemer/blob/74134ef2ab674f2e5a572738ffb0e44b9dee1fc1/lib/json_schemer.rb#L62

From what I can tell, this is the correct behavior according to the spec: http://json-schema.org/understanding-json-schema/structuring.html#the-id-property

**Closed by davishmcclurg** 2020-09-28 17:12 UTC
